services:
  cf-pro-panel:
    image: luofengyuan/cf-pro-panel:latest
    container_name: cf-pro-panel
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # 持久化数据库
      - ./data:/app/data
      # 可选：挂载配置文件
      # - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - PUID=0
      - PGID=0
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=http://127.0.0.1:8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cf_panel_network

networks:
  cf_panel_network:
    driver: bridge
